import './globals.css'
import MyNav from '@/components/Nav';
import Footer from '@/components/Footer';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
          <MyNav />
          <main style={{
            paddingTop: '0px',
            position: 'relative',
            zIndex: '1',
            marginBottom: '140px',
            backgroundColor: 'white',
          }}>
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  )
}
